version: '3.8'
services:
  mysql:
    container_name: xinfeng-mysql
    image: mysql:8
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: newbee_mall_db_v2
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql:/var/lib/mysql/
    networks:
      - xinfeng-network


networks:
  xinfeng-network:
    driver: bridge

volumes:
  mysql:
    driver: local
